package rune;

public enum TypeSymbol {
    //NOURISHING_RUNE
    BASE_NOURISHING_RUNE,

    //SIZE_RUNE
    BIG_SIZE_RUNE,
    MEDIUM_SIZE_RUNE,
    SMALL_SIZE_RUNE,

    //SHAPE_RUNE
    TRIANGLE_SHAPE_RUNE,
    CUBE_SHAPE_RUNE,
    SPHERE_SHAPE_RUNE,
    WOLF_SHAPE_RUNE,

    //CONCENTRATION_ENERGY_RUNE
    BIG_CONCENTRATION_RUNE,
    MEDIUM_CONCENTRATION_RUNE,
    SMALL_CONCENTRATION_RUNE,

    //ENERGY_TYPE_RUNE
    FIRE_ENERGY_RUNE,
    WATER_ENERGY_RUNE,
    EARTH_ENERGY_RUNE,
    AIR_ENERGY_RUNE,
    PURE_ENERGY_RUNE,
    PRANA_ENERGY_RUNE,

    //CYCLE_RUNE
    BASE_CYCLE_RUNE,

    //DIRECTION_RUNE
    LEFT_DIRECTION_RUNE,
    RIGHT_DIRECTION_RUNE,
    FORWARD_DIRECTION_RUNE,
    BACKWARD_DIRECTION_RUNE
    
    //задать типы всех символов у рун, независимо от их типа, без приоритета просто названия.
}
